### ISSUE TITLE
Pocket firmware 2.0: core crashes when changing Display Modes

### ISSUE THREAD

**Issue by davewongillies** [Mazamars312/openfpga-pcengine-cd#49]
On a Pocket running version 2.0 of the firmware changing display modes crashes the PC Engine CD core. Only tested in handheld mode so far.

This seems like it might be when switching to display modes other than Trinitron. I've also managed to crash the regular PCE core.

**Comment by Crimz0N** [comment]
> This seems like it might be when switching to display modes other than Trinitron. I've also managed to crash the regular PCE core.

The original display modes are all working, except the DMG LCD and the Pinball Matrix ones. The problem is, the DMG LCD one is right next to the CRT Trititron one, so if you try to cycle through, you will always hit the DMG LCD one. 

Instead, you should change the display mode from the Pocket Menu. Then you can use all the other working modes. 
Use this method until the DMG and Pinball ones are fixed.

**Comment by Mazamars312** [comment]
I believe this is more of a PocketOS 2.0 issue. Which has been fixed on version 2.1. if you could check and confirm.

**Comment by davewongillies** [comment]
> I believe this is more of a PocketOS 2.0 issue. Which has been fixed on version 2.1. if you could check and confirm.

👍🏻 confirmed that the core no longer crashes on version 2.1
