### ISSUE TITLE
Has this core been abandoned?

### ISSUE THREAD

**Issue by Wesleyrpg** [Mazamars312/openfpga-pcengine-cd#54]
Lots of promises that this core will be updated, yet nothing has been done in over a year and yet the Amiga core has been updated multiple times.

Now that the Analogue OS is up to V2.2 on the Pocket and the Analogue DUO is out there is no more excuses.

Please continue working on updating the core or close it, but don't leave us hanging...

**Comment by mattpannella** [comment]
excuses? you sure seem pretty entitled to someone's free labor

**Comment by Wesleyrpg** [comment]
Not entitlement, just want to know whats going on.

A simple note such as "Working on it" or "Busy with other cores" or "Too hard, no longer interested" would suffice, but the silence is deafening!

**Comment by Mazamars312** [comment]
Its because of stupid comments like this make me not want to do anything more on giving more energy into cores. considering I have already had to drop one core due to other work commitments and working on other larger things at this moment. I have already said I do want to get back on this but would involve a larger MPU re-write to get the timing correct.

I have said this many times before that I am busy at the moment and I want to get the MPU to a more solid standard for many other cores to be easily moved over. This was always a testing core to give people ideas.

**Comment by Wesleyrpg** [comment]
Mazamars, it wasn't a personal attack, i really enjoy your cores and damn you have talent, i just wanted to know what was going on, (even a simple note saying you were busy on other projects)

Sorry you took it personally, it wasn't intended to hurt ya!
