### ISSUE TITLE
allow more .bin files for games? maybe allow different cd format as well.

### ISSUE THREAD

**Issue by ThetaX55** [Mazamars312/openfpga-pcengine-cd#55]
It's kinda annoying to convert the games.
Is there a converter that converts the .bin to 1 in bulk?
Hopefully more format of images supported later? CDH, iso and so on. Maybe allow for it to play the hole image even if it has alot of .bin files.

**Comment by Mazamars312** [comment]
The hard limit on images was not set to myself; this is an Analogue APF limitation. 
As to CDH< I have said many times that this is not doable on my MPU base due to RAM and CPU speed limitations.
If you need more than 26 files, then a single bin file with the cue file to index them is the only way at this moment.
